### ISSUE TITLE
the entry for "one" in the dictionary it actually "any"

### ISSUE THREAD

**Issue by bixfliz** [jeremy-w/orthic#10]
![image](https://user-images.githubusercontent.com/50508846/121826434-36f5f880-cc7d-11eb-9523-4bf292c2590b.png)

**Comment by jeremy-w** [comment]
Yup, that’s wrong.

Viewable at: https://orthic.shorthand.fun/dictionary?q=one&in=text#one

Mis-titled image file: 
https://orthic.shorthand.fun/assets/manual/Specimen_of_Fully-Written_Style_Full_one.png
