### ISSUE TITLE
anki: combine most/must and would/world notes

### ISSUE THREAD

**Issue by rbrewer123** [jeremy-w/orthic#3]
I'm working through the Anki deck, which is hugely helpful for learning the briefs (and is getting me back into Anki along the way). I noticed that most/must map to the same Orthic brief; would/world do too. This means that when presented the Orthic I was often "guessing" the wrong longhand word. I combined the notes in my deck to clarify that most/must both have the same Orthic. I thought you might like to make the changes in your deck.

**Comment by rbrewer123** [comment]
Also into/interest and I'm/him.

**Comment by jeremy-w** [comment]
I considered doing that as I was working through the deck. I found the reminder that those weren’t unique helpful as I worked through it. But perhaps having separate English to Orthic together with a single Orthic to English card for the pairs would have been better.
